packages:
  - apps/*
  - packages/*
  - ui
  - packages/cms/*

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - husky
  - msw 
  - nx
  - sharp
  - unrs-resolver
